### ISSUE TITLE
Support unique secondary indexes

### ISSUE THREAD

**Issue by spetrunia** [MySQLOnRocksDB/mysql-5.6#34]
Initial issue was at
https://github.com/mariadb-corporation/webscalesql-5.6-rocksdb/issues/18

**Comment by hermanlee** [comment]
I can't follow the original link (perhaps permissions), so repasting the information here:

We talked a few months ago that RocksDB SE hasn't supported unique secondary index yet. I'd like to revisit this issue since one of our largest database tiers rely on this feature.

CREATE TABLE ext_assoc_minifeed (
id1 bigint(20) unsigned NOT NULL DEFAULT '0',
id1_type int(10) unsigned NOT NULL DEFAULT '0',
id2 bigint(20) unsigned NOT NULL DEFAULT '0',
id2_type int(10) unsigned NOT NULL DEFAULT '0',
assoc_type bigint(20) unsigned NOT NULL DEFAULT '0',
visibility tinyint(3) NOT NULL DEFAULT '0',
data text NOT NULL,
time int(10) unsigned NOT NULL DEFAULT '0',
version bigint(20) unsigned NOT NULL DEFAULT '0',
ext_data text NOT NULL,
PRIMARY KEY (id1,time,id2),
UNIQUE KEY id2 (id2,id1)
);

mysql> insert into ext_assoc_minifeed (id1, id2, time, data, ext_data) values (1,1,1,'','');
Query OK, 1 row affected (0.00 sec)

mysql> insert into ext_assoc_minifeed (id1, id2, time, data, ext_data) values (1,1,2,'','');
Query OK, 1 row affected (0.00 sec)

mysql> insert into ext_assoc_minifeed (id1, id2, time, data, ext_data) values (1,1,2,'','');
ERROR 1062 (23000): Duplicate entry '1-2-1' for key 'PRIMARY'

The second insert should raise duplicate key error.

The reason why we want unique secondary key is that the biggest data access pattern is "SELECT * FROM ext_assoc_minifeed WHERE id1 = X ORDER BY time DESC LIMIT Y". To make this query faster, we need a clustered index (Primary Key) starting from id1, time. Since Primary Key needs uniqueness, primary key has to be (id1, time, id2). But actual uniqueness is guaranteed by (id1, id2), so we need another real unique index.
@spetrunia spetrunia was assigned by yoshinorim on 2 Oct 2014
@spetrunia
spetrunia commented on 29 Oct 2014

Spec draft:
Uniqueness check

Currently secondary indexes use "extended keys": key value in RocksDB
includes primary key columns. Because of that, one can't check secondary
index unique-ness with a point lookup (i.e. rdb->Get() call). One needs
to do a scan on a prefix that includes only secondary index columns. The scan
will only need to read one row, but it's not a point lookup.

Solutions:
1. Check uniqueness by doing a scan.
2. Switch encoding for unique indexes: PK columns should be in RocksDB's
value, not in the key.

I like # 2 better. It looks like uniqueness checks will be faster when using it.
Concurrency

If there were no concurrent DMLs, uniqueness check would look like so:

try reading the value we're going to write // "the check"
if (found)
 return HA_ERR_DUP_KEY;
write the value; // "the write"

With concurrent writes, we need to prevent this scenario:

thread1> check for valueX (and find it's not present)
thread2> commit, write valueX
thread1> write valueX // unique key violation

it can be done via locking. Locking will work as follows:

 A thread that wishes to modify a unique index (either insert or delete a value), must first acquire a lock (the lock is exclusive)
 Having acquired the lock, it can do a lookup. ** if a duplicate key error occurs, the lock can be released immediately.
 a thread may write the operation into its transaction RowTable.
 the lock will be released when the transaction either commits or aborts.

@spetrunia spetrunia added the enhancement label on 29 Oct 2014
@mdcallag
mdcallag commented on 30 Oct 2014
I like #2 better. For cases when we have a bloom filter on the part of the key that must be unique then we can use KeyMayExist to probe the bloom filter before attempting an index access.
…
@yoshinorim yoshinorim added the bug label on 14 Jan
@spetrunia
spetrunia commented on 3 Feb

Secondary unique key handling should honor @@rocksdb_bulk_load option.
@spetrunia
spetrunia commented on 3 Feb

Input from @yoshinorim : try to have one function to do the check so Read-free-replication can enable/disable unique key checks at one place.
@spetrunia spetrunia referenced this issue in MySQLOnRocksDB/mysql-5.6 on 24 Feb
Open
Support unique secondary indexes #34
