### ISSUE TITLE
Implement repeatable read transaction isolation for RocksDB

### ISSUE THREAD

**Issue by jonahcohen** [MySQLOnRocksDB/mysql-5.6#6]
From @mdcallag:

We currently provide read committed. We need to define and implement repeatable read. See https://github.com/MariaDB/webscalesql-5.6/wiki/Cursor-Isolation

This is a placeholder for now.

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D32355

**Comment by mdcallag** [comment]
How was repeatable read implemented?

On Thu, Feb 5, 2015 at 9:26 AM, Yoshinori Matsunobu <
notifications@github.com> wrote:

> Closed #6 https://github.com/MySQLOnRocksDB/mysql-5.6/issues/6.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MySQLOnRocksDB/mysql-5.6/issues/6#event-230636184.

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by yoshinorim** [comment]
Needs more test cases (and likely implementation) to cover this -- https://github.com/MariaDB/webscalesql-5.6/wiki/Cursor-Isolation

**Comment by mdcallag** [comment]
Decisions to be made:
1) match PG or InnoDB semantics for RR. I think PG is easier to implement but will have more conflicts detected so db users see more errors
2) get snapshot on BEGIN or on first read after BEGIN when RR is used. InnoDB gets snapshot on first read after BEGIN

**Comment by mdcallag** [comment]
Basic test to distinguish between InnoDB and PG RR:
1) trx1: BEGIN
2) trx2: BEGIN
3) trx1: SELECT to establish snapshot (assuming it wasn't set on BEGIN)
4) trx2: SELECT to establish snapshot
5) trx1: UPDATE foo set x=2 where y=1
6) trx1: COMMIT
7) trx2: UPDATE foo set x=3 where y=1

I have not tested this but assume that PG gets an error from the write conflict and InnoDB does not because trx2 will see the version of the row after the COMMIT by trx1
